import React from 'react';

const paragraphs = [
  'Depois de uma eliminação do Brasil em Copa do Mundo, o país costuma procurar um culpado para demonizar. É quase um ritual: alguém precisa sair carregando sozinho uma derrota que, na verdade, foi construída por dezenas de eventos pequenos, alguns controláveis, outros nem tanto. Desta vez, a lista de suspeitos apareceu rápido. Para alguns, o culpado foi Neymar, porque entrou e teria bagunçado o jogo. Para outros, o problema foi justamente ele não ter começado jogando. Há quem olhe para o pênalti perdido e conclua que Vini Júnior deveria ter batido, não Bruno Guimarães. Há quem pergunte se a culpa foi da zaga, que não defendeu o cruzamento decisivo, ou do ataque, que criou e não converteu. Há ainda quem volte para Carlo Ancelotti e suas substituições, como se a mesma caneta que foi chamada de genial contra o Japão tivesse virado, dias depois, a explicação definitiva para tudo que deu errado.',
  'Na Previsão Esportiva, trabalhamos desde 2010 tentando quantificar eventos relacionados à Copa do Mundo. E sabemos bem que probabilidade, quando contraria paixão, vira alvo fácil. Já fomos criticados quando apontamos a Alemanha como favorita em um Mundial e ela caiu ainda na primeira fase. Mas aquela queda não era impossível: estava no mapa, com algo perto de 10% de chance. E 10% acontece. Quando várias seleções grandes entram em uma Copa com algo nessa ordem de risco, a chance de que pelo menos uma delas tropece deixa de ser pequena. Com dez equipes sob risco de 10%, por exemplo, o número esperado de quedas é uma. A surpresa individual continua doendo, mas a existência de surpresas na competição é esperada.',
  'Esse tipo de julgamento tem um problema conhecido no esporte, na estatística e em qualquer situação de incerteza: ele é orientado pelo resultado. É o famoso engenheiro de obra pronta. Primeiro vemos o desfecho; depois reorganizamos a memória para fazer parecer que tudo era óbvio desde o começo. Se a bola entra, a decisão era corajosa. Se a bola bate na trave, era irresponsável. Se a substituição muda o jogo a favor, o treinador é gênio. Se a mesma lógica termina em derrota, era invenção. Só que avaliar uma decisão depois que o placar já contou o fim da história é uma forma muito pobre de entender futebol.',
  'Uma boa decisão pode terminar mal, e uma decisão ruim pode terminar bem. O resultado revela o que aconteceu naquela realização específica, mas não revela sozinho se a decisão era correta. Futebol funciona assim, embora a nossa cultura insista em tratar o jogo como se fosse determinístico. Como se Vini Júnior batendo o pênalti fosse certeza de gol. Como se o pênalti convertido fosse certeza de vitória. Como se Bruno perdendo explicasse, sozinho, toda a eliminação. Como se a presença ou a ausência de Neymar bastasse para organizar ou desorganizar uma partida inteira. O futebol não funciona como uma equação fechada; ele é feito de tendências, margens, escolhas e acontecimentos que só se realizam depois que a bola rola.',
  'Mesmo em um pênalti, que é uma das situações mais favoráveis que um ataque pode ter, ainda existe erro. Existe goleiro, pressão, leitura, escolha de canto, execução, gramado, estado emocional, ruído. Mudar o cobrador pode alterar a probabilidade, claro, mas normalmente altera dentro de uma margem bem menor do que o debate público sugere. Um cobrador melhor não transforma uma cobrança em 100%. Nem os maiores jogadores da história transformam. O ponto não é inocentar um erro técnico, mas lembrar que um erro técnico não é, automaticamente, uma explicação total.',
  'Cristiano Ronaldo é um bom exemplo justamente porque é excepcional. Em bases agregadas, aparece com 184 pênaltis convertidos em 220 cobranças na carreira, taxa de 83,6%. Isso significa 36 erros. Um dos maiores cobradores da história, talvez o maior em volume, também perde mais ou menos uma cobrança a cada seis. Portanto, quando um pênalti é desperdiçado em um jogo grande, não estamos diante de um evento absurdo. Estamos diante de um evento ruim, doloroso, mas perfeitamente compatível com o que acontece até na elite.',
  'Roberto Baggio é outro lembrete cruel. Ele era Bola de Ouro, melhor jogador do mundo, herói italiano em 1994 e um cobrador de altíssimo nível: marcou 108 de 127 pênaltis oficiais na carreira, perto de 85% de aproveitamento. Mesmo assim, perdeu o pênalti decisivo na final da Copa contra o Brasil. A memória pública transformou aquele chute em símbolo, mas aquele chute não apagava quem ele era, nem provava que ele não deveria ter batido. Provava apenas que até os melhores atravessam a parte do jogo em que a probabilidade falha.',
  'O mesmo vale para as chances criadas durante o jogo. O Brasil saiu de novo com a sensação amarga de quem produziu mais, atacou mais, levou mais perigo, acumulou mais expectativa de gol e, ainda assim, ficou pelo caminho. É uma história parecida com a de outras eliminações recentes do nosso futebol: muito volume, muitas chegadas, muitas bolas rondando a área, mas pouca conversão. Às vezes o cruzamento passa centímetros à frente da cabeça de um atacante. Às vezes cai no pé errado. Às vezes o domínio não encaixa. Às vezes a bola que parece pronta para virar gol escapa por um detalhe.',
  'E então a Noruega precisa de um cruzamento. Um. No futebol, muitas vezes são necessários três, quatro, cinco lances parecidos até tudo encaixar: o tempo do passe, o movimento do atacante, o espaço entre zagueiros, a decisão do goleiro. Mas às vezes encaixa de primeira. Não porque havia uma força mística contra o Brasil, nem porque alguém traiu a camisa, nem porque faltou amor. Simplesmente porque o jogo é um conjunto de eventos aleatórios em sequência. As equipes tentam inclinar esses eventos a seu favor. Elas treinam para isso. Mas não controlam tudo.',
  'É por isso que o ponto de vista da Previsão Esportiva é tão incômodo depois de uma derrota: ele não oferece um vilão fácil. Um favorito antes da Copa entra, no melhor dos cenários, com algo como 15% ou 20% de probabilidade de título. Isso é enorme em comparação com os outros, mas ainda é pouco em termos absolutos. É, no máximo, uma face de um dado. Favoritismo não significa promessa; significa competitividade. Significa comprar um espaço maior no universo de possibilidades contra outras seleções que também chegaram ao nível mais alto do esporte.',
  'Treinamento, preparação, elenco, comissão técnica, análise de dados e estratégia servem para aumentar esse espaço amostral. Servem para transformar 5% em 8%, 8% em 12%, 12% em 18%. Isso é muito. Em alto rendimento, é quase tudo. Mas não garante taça. Nenhum modelo sério, nenhum treinador sério e nenhum jogador honesto com a complexidade do jogo deveria vender garantia. O máximo que se pode fazer é chegar melhor, criar mais, escolher melhor, sofrer menos e repetir boas decisões. Depois disso, como diz o ditado de arquibancada, o jogo é jogado e o lambari é pescado. Ainda existe a bola.',
  'Quem quiser um exercício saudável deveria rever os melhores momentos das finais de 1994 e 2002. Mesmo nas Copas em que o Brasil terminou campeão, houve chances perdidas, decisões imperfeitas, ataques desperdiçados, sustos, bolas que poderiam ter mudado o filme. Os nossos atacantes perderam gols. Os adversários também. A diferença é que, quando o troféu vem, essas falhas viram detalhe pitoresco. Quando a eliminação vem, viram prova definitiva de culpa. O lance não mudou de natureza; mudou o resultado que veio depois dele.',
  'Por isso, talvez o verdadeiro culpado pela eliminação do Brasil seja uma resposta frustrante: o futebol. O futebol sendo futebol. A matemática, em expectativa, até pode ter favorecido o Brasil em vários momentos. Mas as realizações concretas dos eventos aleatórios não favoreceram. A seleção podia e devia buscar melhores chances, melhores decisões e maior eficiência. Isso faz parte da análise. O que não faz sentido é transformar jogadores em alvo de ódio, invadir redes sociais, atacar famílias e cobrar deles uma dívida que eles não têm conosco. Esse ódio não é análise; é a humanidade das pessoas se exacerbando em uma de suas formas menos bonitas. A Copa é capaz de produzir cenas lindas, gestos enormes, histórias que atravessam gerações. Mas a quantidade de ataques que fazemos aos nossos próprios jogadores, muitas vezes antes mesmo de a seleção cair, definitivamente não está entre essas belezas.',
  'Não tenho dúvida de que esse ambiente afeta a seleção de alguma maneira, ainda que seja difícil medir quanto disso muda, de fato, uma probabilidade. A verdade é que a seleção brasileira não nos deve mais uma Copa. Ela nos deve a melhor tentativa possível. Em contrapartida, nós, torcedores, devemos apoiar, sofrer junto, até discordar, mas sempre respeitar e focar no apoio aos nossos jogadores e à nossa seleção. Devemos deixar claro que acreditamos no futebol deles e no jogo deles. Eu acredito muito na experiência do Mister Ancelotti e acredito que teremos uma excelente chance na próxima Copa, com o trabalho que será desenvolvido nos próximos quatro anos. Que venha o hexa em 2030!',
];

const subtitle =
  'Depois de um pênalti perdido, uma substituição contestada e uma eliminação dolorosa, a pergunta talvez não seja quem errou, mas por que precisamos tanto de um culpado.';

const BrazilEliminationChroniclePage: React.FC = () => (
  <div className="min-h-screen bg-brand-light text-brand-dark">
    <section className="border-b border-brand-dark/10 bg-white">
      <div className="mx-auto max-w-[1080px] px-4 py-12 text-center md:py-14">
        <p className="font-montserrat text-xs font-black uppercase tracking-widest text-brand-green">Opinião</p>
        <h1 className="mx-auto mt-3 max-w-4xl text-center font-montserrat text-3xl font-black uppercase leading-[1.04] tracking-tight text-brand-dark md:text-4xl lg:text-[2.9rem]">
          O verdadeiro culpado pela eliminação do Brasil na Copa do Mundo
        </h1>
        <p className="mx-auto mt-6 max-w-3xl text-base leading-relaxed text-brand-dark/68 md:text-lg">
          {subtitle}
        </p>
      </div>
    </section>

    <main className="mx-auto max-w-[1080px] px-4 py-12 md:py-14">
      <article className="mx-auto max-w-[1080px] space-y-7 text-[1.05rem] leading-[1.9] text-brand-dark/78 md:text-lg">
        {paragraphs.map((paragraph, index) => (
          <p key={index}>{paragraph}</p>
        ))}
      </article>

      <div className="mx-auto mt-12 max-w-[1080px] border-t border-brand-dark/10 pt-8 text-center">
        <p className="font-montserrat text-sm font-black uppercase tracking-wider text-brand-dark">Ricardo Rocha</p>
        <p className="mt-1 text-sm font-semibold text-brand-dark/65">Coordenador da Previsão Esportiva.</p>
        <p className="mt-1 text-xs font-semibold text-brand-dark/45">Não o campeão de 94, é outro.</p>
      </div>
    </main>
  </div>
);

export default BrazilEliminationChroniclePage;
